version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: weekly
      day: tuesday
      time: "03:00"
      timezone: Europe/London
    groups:
      npm:
        patterns:
          - "*"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
      day: "friday"
      time: "09:00"
